name: 'Code Limit'
description: 'Your Refactoring Alarm ⏰'
branding:
  icon: 'activity'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  token:
    description: 'GitHub token for GitHub API requests'
    required: true
    default: ${{ github.token }}
