name: 'Code Limit'
description: 'Your Refactoring Alarm ⏰'
branding:
  icon: 'activity'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  token:
    description: 'GitHub token for repository'
    default: ${{ github.token }}
    required: false
  check:
    description: 'Checked changed files'
    default: 'true'
    required: false
  excludes:
    description: 'Extra exclude patterns to pass to Code Limit'
    default: []
    required: false
