name: 'Code Limit'
description: 'Your Refactoring Alarm ⏰'
branding:
  icon: 'activity'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  upload:
    description: 'Upload report to Code Limit'
    required: false
  token:
    description: 'GitHub token used for upload to Code Limit'
    required: false
