name: 'CodeLimit'
description: 'Your Refactoring Alarm ⏰'
branding:
  icon: 'activity'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  token:
    description: 'GitHub token for storing results'
    required: false
    default: ${{ github.token }}
  check:
    description: 'Check changed files'
    required: false
    default: true
  codelimit-version:
    description: 'CodeLimit version'
    required: false
    default: 'latest'