name: 'Code Limit'
description: 'Your Refactoring Alarm ⏰'
branding:
  icon: 'activity'
  color: 'orange'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  token:
    description: 'GitHub token for repository'
    required: true
  check:
    description: 'Checked changed files'
    default: 'true'
    required: false
  upload:
    description: 'Upload report to Code Limit'
    default: 'false'
    required: false
