name: codelimit

on:
  workflow_run:
    workflows: [main]
    types:
      - completed

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v6

    - name: Run CodeLimit main version
      uses: getcodelimit/codelimit-action@main
      with:
        check: false
        codelimit_version: 'latest'

    - name: Run CodeLimit v1 version
      uses: getcodelimit/codelimit-action@v1
        check: false
