name: codelimit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v6

    - name: Run CodeLimit main version
      uses: getcodelimit/codelimit-action@main
      with:
        codelimit_version: 'latest'

    - name: Run CodeLimit v1 version
      uses: getcodelimit/codelimit-action@v1
