name: 'main'

on:
  push:
    branches:
      - main
  pull_request:
    branches: main

jobs:
  main:
    if: github.repository == 'getcodelimit/codelimit-action'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: 'Checkout sources'
      uses: actions/checkout@v4

    - name: 'Setup Node'
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: 'Install dependencies'
      run: yarn install

    - name: 'Run Code Limit action'
      uses: getcodelimit/codelimit-action@main
