name: 'main'
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: 'Check token'
      run: |
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/installation/repositories
    - name: 'Show env vars'
      run: |
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Repository: $GITHUB_REF_NAME"
    - name: 'Checkout sources'
      uses: actions/checkout@v3
    - name: 'Setup NodeJS'
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: 'Install dependencies'
      run: npm install
