name: main

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout sources
      uses: actions/checkout@v7

    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: '24.x'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build dist
      run: npm run dist

    - name: Commit dist
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Distribution build
